"""Add category and payment fields

Revision ID: 3f0542dd0f82
Revises: 4ba507cf3bf3
Create Date: 2026-02-23 08:09:15.589784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f0542dd0f82'
down_revision: Union[str, Sequence[str], None] = '4ba507cf3bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('payment_status', sa.String(length=20), nullable=False, server_default='PENDING'))
    op.add_column('bookings', sa.Column('payment_link', sa.String(length=255), nullable=True))
    op.add_column('bookings', sa.Column('payment_reference_id', sa.String(length=100), nullable=True))
    op.add_column('loads', sa.Column('category', sa.String(length=50), nullable=False, server_default='General'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loads', 'category')
    op.drop_column('bookings', 'payment_reference_id')
    op.drop_column('bookings', 'payment_link')
    op.drop_column('bookings', 'payment_status')
    # ### end Alembic commands ###
