"""add conversation sessions

Revision ID: 4ba507cf3bf3
Revises: 
Create Date: 2026-02-23 07:40:46.875655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ba507cf3bf3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('current_flow', sa.String(length=50), nullable=False),
    sa.Column('current_step', sa.String(length=50), nullable=False),
    sa.Column('collected_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_sessions_phone_number'), 'conversation_sessions', ['phone_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('DRIVER', 'SHIPPER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('loads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipper_id', sa.UUID(), nullable=False),
    sa.Column('pickup_city', sa.String(), nullable=False),
    sa.Column('drop_city', sa.String(), nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=False),
    sa.Column('pickup_lng', sa.Float(), nullable=False),
    sa.Column('drop_lat', sa.Float(), nullable=False),
    sa.Column('drop_lng', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipper_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loads_drop_city'), 'loads', ['drop_city'], unique=False)
    op.create_index(op.f('ix_loads_pickup_city'), 'loads', ['pickup_city'], unique=False)
    op.create_index(op.f('ix_loads_shipper_id'), 'loads', ['shipper_id'], unique=False)
    op.create_index(op.f('ix_loads_status'), 'loads', ['status'], unique=False)
    op.create_table('trucks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('source_city', sa.String(), nullable=False),
    sa.Column('destination_city', sa.String(), nullable=False),
    sa.Column('source_lat', sa.Float(), nullable=False),
    sa.Column('source_lng', sa.Float(), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=False),
    sa.Column('dest_lng', sa.Float(), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('capacity_total', sa.Float(), nullable=False),
    sa.Column('capacity_available', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trucks_destination_city'), 'trucks', ['destination_city'], unique=False)
    op.create_index(op.f('ix_trucks_driver_id'), 'trucks', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trucks_source_city'), 'trucks', ['source_city'], unique=False)
    op.create_index(op.f('ix_trucks_status'), 'trucks', ['status'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('truck_id', sa.UUID(), nullable=False),
    sa.Column('load_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_load_id'), 'bookings', ['load_id'], unique=False)
    op.create_index(op.f('ix_bookings_truck_id'), 'bookings', ['truck_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_truck_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_load_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_trucks_status'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_source_city'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_driver_id'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_destination_city'), table_name='trucks')
    op.drop_table('trucks')
    op.drop_index(op.f('ix_loads_status'), table_name='loads')
    op.drop_index(op.f('ix_loads_shipper_id'), table_name='loads')
    op.drop_index(op.f('ix_loads_pickup_city'), table_name='loads')
    op.drop_index(op.f('ix_loads_drop_city'), table_name='loads')
    op.drop_table('loads')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_conversation_sessions_phone_number'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    # ### end Alembic commands ###
