"""Add booking reference and expiry

Revision ID: 71234f1c7ec5
Revises: 3f0542dd0f82
Create Date: 2026-02-23 08:17:56.602433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71234f1c7ec5'
down_revision: Union[str, Sequence[str], None] = '3f0542dd0f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_reference_id', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('payment_expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_bookings_booking_reference_id'), 'bookings', ['booking_reference_id'])
    op.create_unique_constraint('uq_bookings_booking_reference_id', 'bookings', ['booking_reference_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_bookings_booking_reference_id', 'bookings', type_='unique')
    op.drop_index(op.f('ix_bookings_booking_reference_id'), table_name='bookings')
    op.drop_column('bookings', 'payment_expires_at')
    op.drop_column('bookings', 'booking_reference_id')
    # ### end Alembic commands ###
